GET http://localhost:8080/api/chat HTTP/2.0

###

POST http://localhost:8080/api/chat HTTP/1.1
content-type: application/json

{
    "idCreador": "bd4d4f16-5ce9-404b-a20c-c1cf849ae226",
    "tipo": "GRUPO",
    "nombre": "ona brrrcxzfzdrrrrrrrrr"
}

###

PUT  http://localhost:8080/api/chat HTTP/1.1
content-type: application/json

{
    "id": "f99bd93b-2739-43ea-aa5f-c1af4b88b6da",
    "nombre": "Se acfdsgdgfgtualizo"
}

###

PATCH  http://localhost:8080/api/chat HTTP/2.0