spring.application.name=chat

server.address=0.0.0.0
server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.com.jesus.proyecto=${LOGGING_LEVEL_APP:WARN}
logging.level.org.springframework.web=${LOG_LEVEL_WEB:WARN}
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=${LOG_LEVEL_FILTER:ERROR}

jwt.secret.key=${JWT_SECRET_KEY}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION:5m}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION:7d}
jwt.refresh.rotation=${JWT_REFRESH_ROTATION:4d}

file.max-size-mb=${FILE_MAX_SIZE_MB:50}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

openai.api.key=${OPENAI_API_KEY}
openai.api.url=${OPENAI_API_URL}
openai.model=${OPENAI_MODEL}

openai.api.audio.key=${OPENAI_API_AUDIO_KEY}
openai.api.audio.url=${OPENAI_API_AUDIO_URL}
openai.audio.model=${OPENAI_AUDIO_MODEL:whisper-large-v3}