version: '3'

services:
  app_chat:
    mem_limit: 3g
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL} 
      DB_USER_NAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_PASSWORD}

      SERVER_PORT: ${SERVER_PORT}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      JWT_REFRESH_ROTATION: ${JWT_REFRESH_ROTATION}

      FILE_MAX_SIZE_MB: ${FILE_MAX_SIZE_MB}

      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_URL: ${OPENAI_API_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}

      OPENAI_API_AUDIO_KEY: ${OPENAI_API_AUDIO_KEY}
      OPENAI_API_AUDIO_URL: ${OPENAI_API_AUDIO_URL}
      OPENAI_AUDIO_MODEL: ${OPENAI_AUDIO_MODEL}

    restart: always