### 1. Listar todos los usuarios
GET http://localhost:8080/api/usuario

### 2. Listar todos (con slash)
GET http://localhost:8080/api/usuario/


### 3. Registrar usuario (JSON)
POST http://localhost:8080/api/usuario
Content-Type: application/json

{
    "usuario": "juan123",
    "nombre": "Juan Perez",
    "password": "1234"
}


### 4. Buscar por ID (válido)
GET http://localhost:8080/api/usuario?id=bd4d4f16-5ce9-404b-a20c-c1cf849ae226


### 1. Listar todos los usuarios
GET http://localhost:8080/api/msg